apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: rimfire-jwt-auth
build:
  artifacts:
    - image: rimfire-jwt-auth
      context: .
      jib: {}
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
