micronaut:
  application:
    name: rimfire-jwt-auth
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: your-secret-key-here-with-at-least-32-characters
  server:
    port: 2222
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/rimfirededb
    driver-class-name: org.postgresql.Driver
    dialect: POSTGRES
    username: rimfirededb
    password: mysecretpassword
